### ISSUE TITLE
Test across multiple app screen sizes (iOS)

### ISSUE THREAD

**Issue by clarle** [codeforsanjose/open311-ionic#16]
We'll be doing a bug bash at the next meetup for multiple different iOS devices.

Our goal is to fix any styling issues that we see in any of the devices - targeting the 3.5", 4", 4.7", and 5.5" phones.

We'll assign a different phone to each person to quickly verify that all of the screens look good.
- [ ] iPhone 4s
- [ ] iPhone 5s
- [ ] iPhone 6
- [ ] iPhone 6 Plus

**Comment by arichen** [comment]
I am collecting testers and ensure there are at least one tester for each phone model.  Target time to start testing is 4/11.
