### ISSUE TITLE
New Request: Camera screen displaced

### ISSUE THREAD

**Issue by arichen** [codeforsanjose/open311-ionic#21]
Status bar is overlapping the camera section.

**Device:** iPhone 5S
**Image:**
![img_7615](https://cloud.githubusercontent.com/assets/8155256/14900730/ea783af4-0d46-11e6-8c18-f34661b720de.png)

**Comment by ghost** [comment]
Also, looks like the transparency/opacity should be improved. It's tough to view the dialog. Thoughts?
