### ISSUE TITLE
New Request: Location

### ISSUE THREAD

**Issue by arichen** [codeforsanjose/open311-ionic#23]
1. Address input box
2. Current location
3. Movable pin

**Comment by ghost** [comment]
Here's the requirements from the spec as a FYI:

Provide location information. If photo(s) is/are provided, the app will try to extract location information from the photo(s) if possible, and auto-fill the location information. If no photo(s) provided, user will choose a location from map. Required field.

**Comment by ghost** [comment]
The location pin and the text-based format is working as well. A couple of issues cropped up:
- The map doesn't move/center to the pin if it's off the center of the map
- The text field is off center and height to the pin button.

Would be good to have Shivani take a look and provide some design direction here. I'd say that both should be at the same height and there should be a greater space to view the address that's inputted in.

**Comment by ghost** [comment]
This is working now; worth closing @arichen ?
