### ISSUE TITLE
Users can add a title to the request form

### ISSUE THREAD

**Issue by ghost** [codeforsanjose/open311-ionic#27]
Based off of the requirements:

Input issue title. Default title is pre-filled based on the issue type chosen. Required field.

A few considerations:
- Form validation on the field.
- Limits to the length of the title field.

**Comment by ghost** [comment]
Title can be added to the form. @arichen I didn't see form validation, is this completely ready?

**Comment by arichen** [comment]
@tapomay added form validation in 97e0e079b265cc6edc51d93ae917de02f1236cc1
I added limitation for title in 0272282ccd3f5ead3aa5f5d63ee8b35479e475e9
