### ISSUE TITLE
Users can view recently filed requests

### ISSUE THREAD

**Issue by ghost** [codeforsanjose/open311-ionic#32]
User will see a list of nearby reported issues based on location provided. Location is editable by user:
- Location. Default location is user’s current location. User can modify the location on a map or through search by address.
- Radius. A default radius is provided. User can modify the preferred search radius.

Product Spec:
https://docs.google.com/document/d/1v15wkPoYwXVt8KZD_FEuaFr4z7rujGFlCEcXuCTI51I/edit?usp=sharing

**Comment by arichen** [comment]
This section is partially done.
Currently is uses hard coded location, @tapomay is working on grabbing user current location.

**Comment by arichen** [comment]
This section is done
