### ISSUE TITLE
Add a "no recent requests" text to the Recent Page

### ISSUE THREAD

**Issue by ghost** [codeforsanjose/open311-ionic#45]
For a blank Recent page (i.e. when there aren't any recently filed requests), there should be text that notes that the user needs to file a request. Also, add a button that links back to the request form on the page.

Example Text (1): "Hey!"
Example Text (2): "You still need to send your first request to the city."

Button Text: "Send a Request".

**Comment by arichen** [comment]
@tapomay added the alert
